const API_BASE='https://br-autumn-rice-b5twaf7e-catalogapi.compute.c-7.us-east-2.aws.neon.tech';

const UI={
ru:{navExplore:'Каталог',navCategories:'Категории',navCities:'Города',heroBadge:'КАТАЛОГ МЕСТ И БИЗНЕСОВ ИЗРАИЛЯ',heroTitle:'Найдите любое место в Израиле.',heroSub:'Рестораны, фастфуд, магазины, супермаркеты, аптеки, отели, АЗС и сервисы — в одном понятном каталоге с фото и навигацией.',heroLine:'РЕСТОРАНЫ  •  МАГАЗИНЫ  •  АПТЕКИ  •  ОТЕЛИ  •  СЕРВИСЫ',searchPh:'Что вы ищете? Например: shawarma, IKEA, pharmacy…',cityAll:'Весь Израиль',search:'Найти место',stat1:'официальных населённых пунктов',stat2:'мест и бизнесов в каталоге',stat3:'населённых пунктов с точками',stat4:'языка интерфейса',livePlaces:'Популярные и новые места',liveSub:'Карточки реальных точек из каталога Israel Places',cities:'Выберите город или населённый пункт',citiesSub:'Перейдите в локальный каталог вашего города',view:'Смотреть все',places:'мест',results:'Каталог мест',all:'Все категории',details:'Открыть место',info:'Информация',phone:'Телефон',website:'Сайт',coordinates:'Координаты',address:'Адрес',source:'Источники данных',back:'← Назад',loading:'Загружаю Israel Places…',notFound:'Ничего не найдено. Измените запрос, город или категорию.',live:'АКТИВНО',dataNote:'Israel Places — каталог мест и бизнеса Израиля. Данные объединяются из открытых и разрешённых источников и постоянно уточняются.',gallery:'Фотографии места',googleMaps:'Google Maps',waze:'Waze',navigate:'Построить маршрут',noPhoto:'Фото пока не найдено',categories:'Что вы хотите найти?',categoriesSub:'Выберите категорию и сразу перейдите к нужным местам',introTitle:'Вы находитесь в Israel Places',introText:'Здесь можно найти бизнес или место по всему Израилю, открыть карточку, посмотреть фото и сразу построить маршрут.',step1:'1. Найдите место',step2:'2. Откройте карточку',step3:'3. Постройте маршрут'},
he:{navExplore:'קטלוג',navCategories:'קטגוריות',navCities:'יישובים',heroBadge:'מדריך מקומות ועסקים בישראל',heroTitle:'מצאו כל מקום בישראל.',heroSub:'מסעדות, מזון מהיר, חנויות, סופרמרקטים, בתי מרקחת, מלונות, תחנות דלק ושירותים — במקום אחד עם תמונות וניווט.',heroLine:'מסעדות  •  חנויות  •  בתי מרקחת  •  מלונות  •  שירותים',searchPh:'מה מחפשים? לדוגמה: shawarma, IKEA, pharmacy…',cityAll:'כל ישראל',search:'חיפוש מקום',stat1:'יישובים רשמיים',stat2:'מקומות ועסקים במאגר',stat3:'יישובים עם נקודות',stat4:'שפות בממשק',livePlaces:'מקומות פופולריים וחדשים',liveSub:'כרטיסים אמיתיים ממדריך Israel Places',cities:'בחרו עיר או יישוב',citiesSub:'עברו למדריך המקומי של היישוב',view:'הצגת הכל',places:'מקומות',results:'קטלוג מקומות',all:'כל הקטגוריות',details:'פתיחת מקום',info:'מידע',phone:'טלפון',website:'אתר',coordinates:'קואורדינטות',address:'כתובת',source:'מקורות מידע',back:'→ חזרה',loading:'טוען Israel Places…',notFound:'לא נמצאו תוצאות. שנו חיפוש, יישוב או קטגוריה.',live:'פעיל',dataNote:'Israel Places — מדריך מקומות ועסקים בישראל. הנתונים מאוחדים ממקורות פתוחים ומורשים ומתעדכנים באופן שוטף.',gallery:'תמונות המקום',googleMaps:'Google Maps',waze:'Waze',navigate:'ניווט',noPhoto:'עדיין אין תמונה',categories:'מה תרצו למצוא?',categoriesSub:'בחרו קטגוריה ועברו ישירות למקומות המתאימים',introTitle:'אתם ב-Israel Places',introText:'כאן אפשר למצוא עסקים ומקומות בכל ישראל, לפתוח כרטיס, לראות תמונות ולנווט מיד.',step1:'1. חפשו מקום',step2:'2. פתחו כרטיס',step3:'3. נווטו'},
en:{navExplore:'Directory',navCategories:'Categories',navCities:'Cities',heroBadge:'ISRAEL BUSINESS & PLACES DIRECTORY',heroTitle:'Find any place in Israel.',heroSub:'Restaurants, fast food, shops, supermarkets, pharmacies, hotels, fuel stations and services — one clear directory with photos and navigation.',heroLine:'RESTAURANTS  •  SHOPS  •  PHARMACIES  •  HOTELS  •  SERVICES',searchPh:'What are you looking for? e.g. shawarma, IKEA, pharmacy…',cityAll:'All Israel',search:'Find a place',stat1:'official localities',stat2:'places and businesses in the catalog',stat3:'localities with places',stat4:'interface languages',livePlaces:'Popular and new places',liveSub:'Real listings from the Israel Places catalog',cities:'Choose a city or locality',citiesSub:'Open the local directory for your area',view:'View all',places:'places',results:'Places directory',all:'All categories',details:'Open place',info:'Information',phone:'Phone',website:'Website',coordinates:'Coordinates',address:'Address',source:'Data sources',back:'← Back',loading:'Loading Israel Places…',notFound:'Nothing found. Change the search, locality or category.',live:'ACTIVE',dataNote:'Israel Places is a directory of places and businesses in Israel. Data is merged from open and permitted sources and continuously refined.',gallery:'Place photos',googleMaps:'Google Maps',waze:'Waze',navigate:'Get directions',noPhoto:'Photo not found yet',categories:'What do you want to find?',categoriesSub:'Choose a category and jump straight to matching places',introTitle:'You are in Israel Places',introText:'Find businesses and places across Israel, open a listing, see photos and navigate immediately.',step1:'1. Find a place',step2:'2. Open the listing',step3:'3. Navigate'}
};

const CAT={
'amenity:restaurant':['Ресторан','מסעדה','Restaurant'],'amenity:cafe':['Кафе','בית קפה','Cafe'],'amenity:fast_food':['Фастфуд','מזון מהיר','Fast food'],'amenity:bar':['Бар','בר','Bar'],'amenity:pub':['Паб','פאב','Pub'],'amenity:food_court':['Фуд-корт','מתחם אוכל','Food court'],'amenity:ice_cream':['Мороженое','גלידה','Ice cream'],
'shop:bakery':['Пекарня','מאפייה','Bakery'],'shop:confectionery':['Кондитерская','קונדיטוריה','Confectionery'],'shop:supermarket':['Супермаркет','סופרמרקט','Supermarket'],'shop:convenience':['Минимаркет','מכולת','Convenience store'],'shop:kiosk':['Киоск','קיוסק','Kiosk'],'shop:butcher':['Мясной магазин','אטליז','Butcher'],'shop:greengrocer':['Овощи и фрукты','ירקן','Greengrocer'],
'amenity:pharmacy':['Аптека','בית מרקחת','Pharmacy'],'amenity:fuel':['АЗС','תחנת דלק','Fuel station'],'amenity:bank':['Банк','בנק','Bank'],'amenity:clinic':['Клиника','מרפאה','Clinic'],'tourism:hotel':['Отель','מלון','Hotel']
};

const GROUPS=[
['01','amenity:restaurant','Рестораны','מסעדות','Restaurants'],
['02','amenity:fast_food','Фастфуд','מזון מהיר','Fast food'],
['03','amenity:cafe','Кафе','בתי קפה','Cafés'],
['04','shop:supermarket','Супермаркеты','סופרמרקטים','Supermarkets'],
['05','shop:convenience','Минимаркеты','מכולות','Convenience'],
['06','shop:bakery','Пекарни','מאפיות','Bakeries'],
['07','amenity:pharmacy','Аптеки','בתי מרקחת','Pharmacies'],
['08','shop:','Все магазины','כל החנויות','All shops']
];

let lang=localStorage.getItem('foodrate-lang')||'ru';
const tr=k=>UI[lang][k]||k;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const qs=o=>new URLSearchParams(Object.entries(o).filter(([,v])=>v!==''&&v!=null)).toString();
async function api(route,params={}){const r=await fetch(API_BASE+'/'+route+(Object.keys(params).length?'?'+qs(params):''));if(!r.ok)throw new Error('API '+r.status);return r.json()}
function setLang(l){lang=l;localStorage.setItem('foodrate-lang',l);document.documentElement.lang=l;document.documentElement.dir=l==='he'?'rtl':'ltr';renderPage()}
function cityName(c){const fallback=lang==='he'?'ישראל':lang==='ru'?'Израиль':'Israel';return lang==='he'?(c.name_he||c.city_he||c.name_en||c.city_en||fallback):lang==='ru'?(c.name_ru||c.city_ru||c.name_en||c.city_en||c.name_he||c.city_he||fallback):(c.name_en||c.city_en||c.name_he||c.city_he||fallback)}
function placeName(p){return lang==='he'?(p.name_he||p.primary_name):lang==='ru'?(p.name_ru||p.name_he||p.name_en||p.primary_name):(p.name_en||p.primary_name||p.name_he)}
function categoryName(v){const a=CAT[v];return a?(lang==='ru'?a[0]:lang==='he'?a[1]:a[2]):String(v||'').replace(/^.*:/,'').replaceAll('_',' ')}
function icon(v){if(v==='amenity:restaurant')return'🍽️';if(v==='amenity:cafe')return'☕';if(v==='amenity:fast_food')return'🥙';if(v==='shop:bakery')return'🥐';if(v?.startsWith('shop:'))return'🛍️';if(v==='amenity:pharmacy')return'💊';if(v==='amenity:fuel')return'⛽';if(v==='amenity:bar'||v==='amenity:pub')return'🍸';if(v?.startsWith('tourism:'))return'🏨';return'📍'}
function groupLabel(g){return lang==='ru'?g[2]:lang==='he'?g[3]:g[4]}
function nav(){return '<header class="topbar"><div class="shell nav"><a class="brand" href="index.html"><img class="brandLogo" src="logo.svg" alt="Israel Places"></a><nav class="navlinks"><a href="search.html">'+tr('navExplore')+'</a><a href="index.html#categories">'+tr('navCategories')+'</a><a href="index.html#cities">'+tr('navCities')+'</a></nav><div class="navtools"><span class="countryMark">IL</span><button class="lang" data-lang="he">HE</button><button class="lang" data-lang="ru">RU</button><button class="lang" data-lang="en">EN</button></div></div></header>'}
function footer(){return '<footer class="footer"><div class="shell footerIn"><img src="logo.svg" class="footerLogo" alt="Israel Places"><div class="legal">'+tr('dataNote')+'<br>© OpenStreetMap contributors</div></div></footer>'}
function loading(){return nav()+'<main class="section"><div class="shell"><div class="empty">'+tr('loading')+'</div></div></main>'+footer()}
function photo(p){return p.photo_url?'<img src="'+esc(p.photo_url)+'" alt="'+esc(placeName(p))+'" loading="lazy" referrerpolicy="no-referrer">':'<div class="noPhoto"><span>'+icon(p.category)+'</span><small>'+tr('noPhoto')+'</small></div>'}
function placeCard(p){return '<a class="card" href="restaurant.html?id='+encodeURIComponent(p.id)+'"><div class="cover">'+photo(p)+'<span class="badge">'+esc(categoryName(p.category))+'</span></div><div class="cardbody"><div class="cardtop"><div><h3>'+esc(placeName(p))+'</h3><div class="meta"><span class="pinDot"></span>'+esc(cityName(p))+'</div></div></div><div class="tags">'+(p.phone?esc(p.phone):esc(categoryName(p.category)))+'</div><div class="dishrow"><span>'+tr('details')+'</span><strong>↗</strong></div></div></a>'}
function cityCard(c){return '<a class="city" href="city.html?id='+encodeURIComponent(c.official_code)+'"><div><span class="cityCode">IL</span><strong>'+esc(cityName(c))+'</strong></div><span>'+Number(c.places||0).toLocaleString()+' '+tr('places')+'</span><b>↗</b></a>'}
function categoryStrip(){return '<section class="section" id="categories"><div class="shell"><div class="sectionHead"><div><span class="goldKicker">DISCOVER</span><h2>'+tr('categories')+'</h2><p>'+tr('categoriesSub')+'</p></div><a class="textLink" href="search.html">'+tr('view')+' →</a></div><div class="categoryGrid">'+GROUPS.map(g=>'<a class="categoryTile" href="search.html?category='+encodeURIComponent(g[1])+'"><span class="categoryIndex">'+g[0]+'</span><strong>'+esc(groupLabel(g))+'</strong><span class="categoryArrow">↗</span></a>').join('')+'</div></div></section>'}
function pager(total,page,size,params,base){const pages=Math.max(1,Math.ceil(Number(total||0)/size));if(pages<=1)return'';const label=lang==='he'?'עמוד':lang==='ru'?'Страница':'Page';const prev=lang==='he'?'הקודם':lang==='ru'?'Назад':'Previous';const next=lang==='he'?'הבא':lang==='ru'?'Вперёд':'Next';const href=n=>base+'?'+qs({...params,page:n});return '<nav class="pager">'+(page>1?'<a class="pageBtn" href="'+href(page-1)+'">← '+prev+'</a>':'<span></span>')+'<strong>'+label+' '+page+' / '+pages+'</strong>'+(page<pages?'<a class="pageBtn" href="'+href(page+1)+'">'+next+' →</a>':'<span></span>')+'</nav>'}

async function home(){
 const [stats,cities,places]=await Promise.all([api('stats'),api('cities',{limit:8}),api('places',{limit:9})]);
 const featured=places.places.slice(0,3);
 const visual=featured.length?'<div class="heroVisual">'+featured.map((p,i)=>'<a class="heroPlace heroPlace'+i+'" href="restaurant.html?id='+encodeURIComponent(p.id)+'"><div class="heroPlaceMedia">'+photo(p)+'</div><div class="heroPlaceMeta"><span>'+esc(categoryName(p.category))+'</span><strong>'+esc(placeName(p))+'</strong><small>'+esc(cityName(p))+'</small></div></a>').join('')+'</div>':'';
 return nav()+'<main>'+
 '<section class="hero"><div class="shell"><div class="heroGrid">'+
 '<div class="heroCopy"><div class="heroCrumb">ISRAEL PLACES <span>/</span> '+tr('heroBadge')+'</div><span class="eyebrow">'+tr('heroBadge')+'</span><h1>'+tr('heroTitle')+'</h1><p>'+tr('heroSub')+'</p>'+
 '<form class="searchbar" onsubmit="return goSearch(event)"><div class="field searchMain"><span class="searchIcon">⌕</span><input id="q" placeholder="'+tr('searchPh')+'"></div><div class="field cityField"><span>⌖</span><select id="city"><option value="">'+tr('cityAll')+'</option>'+cities.cities.map(c=>'<option value="'+esc(c.official_code)+'">'+esc(cityName(c))+'</option>').join('')+'</select></div><button class="primary">'+tr('search')+'</button></form>'+
 '<div class="heroProof"><span>'+Number(stats.places).toLocaleString()+' '+tr('places')+'</span><i></i><span>'+Number(stats.localities_with_places).toLocaleString()+' '+tr('stat3')+'</span><i></i><span>Google Maps + Waze</span></div></div>'+
 visual+
 '</div>'+
 '<div class="statsBar"><div><strong>'+Number(stats.places).toLocaleString()+'</strong><span>'+tr('stat2')+'</span></div><div><strong>'+Number(stats.localities_with_places).toLocaleString()+'</strong><span>'+tr('stat3')+'</span></div><div><strong>'+Number(stats.localities).toLocaleString()+'</strong><span>'+tr('stat1')+'</span></div><div><strong>3</strong><span>'+tr('stat4')+'</span></div></div>'+
 '</div></section>'+
 categoryStrip()+
 '<section class="section catalogSection"><div class="shell"><div class="sectionHead"><div><span class="goldKicker">EXPLORE</span><h2>'+tr('livePlaces')+'</h2><p>'+tr('liveSub')+'</p></div><a class="textLink" href="search.html">'+tr('view')+' →</a></div><div class="grid">'+places.places.map(placeCard).join('')+'</div></div></section>'+
 '<section class="section citiesSection" id="cities"><div class="shell"><div class="sectionHead"><div><span class="goldKicker">LOCAL DIRECTORY</span><h2>'+tr('cities')+'</h2><p>'+tr('citiesSub')+'</p></div></div><div class="cityGrid">'+cities.cities.map(cityCard).join('')+'</div></div></section>'+
 '</main>'+footer()
}

async function searchPage(){
 const p=new URLSearchParams(location.search),q=p.get('q')||'',city=p.get('city')||'',category=p.get('category')||'',page=Math.max(1,Number(p.get('page')||1)),size=60,offset=(page-1)*size;
 const [cities,places]=await Promise.all([api('cities',{limit:1400}),api('places',{q,city,category,limit:size,offset})]);
 const total=Number(places.total??places.count??0),pages=pager(total,page,size,{q,city,category},'search.html');
 return nav()+'<main class="section"><div class="shell"><div class="sectionHead"><div><span class="goldKicker">SEARCH</span><h2>'+tr('results')+'</h2><p>'+total.toLocaleString()+' '+tr('places')+'</p></div></div><form class="filterPanel" onsubmit="return filterSearch(event)"><input id="fq" value="'+esc(q)+'" placeholder="'+tr('searchPh')+'"><select id="fcity"><option value="">'+tr('cityAll')+'</option>'+cities.cities.map(c=>'<option value="'+esc(c.official_code)+'" '+(city===String(c.official_code)?'selected':'')+'>'+esc(cityName(c))+' ('+Number(c.places||0)+')</option>').join('')+'</select><select id="fcategory"><option value="">'+tr('all')+'</option>'+GROUPS.map(g=>'<option value="'+esc(g[1])+'" '+(category===g[1]?'selected':'')+'>'+g[0]+' '+esc(groupLabel(g))+'</option>').join('')+'</select><button class="primary">'+tr('search')+'</button></form>'+(places.places.length?'<div class="grid">'+places.places.map(placeCard).join('')+'</div>'+pages:'<div class="empty">'+tr('notFound')+'</div>')+'</div></main>'+footer()
}

async function cityPage(){
 const p=new URLSearchParams(location.search),id=p.get('id')||'',page=Math.max(1,Number(p.get('page')||1)),size=60,offset=(page-1)*size;
 const [cities,places]=await Promise.all([api('cities',{limit:1400}),api('places',{city:id,limit:size,offset})]);
 const c=cities.cities.find(x=>String(x.official_code)===String(id));
 if(!c)return nav()+'<main class="section"><div class="shell"><div class="empty">'+tr('notFound')+'</div></div></main>'+footer();
 const total=Number(places.total??c.places??0),pages=pager(total,page,size,{id},'city.html');
 return nav()+'<main><section class="detailHero"><div class="shell"><div class="cityHero"><span class="goldKicker">LOCAL DIRECTORY</span><h1>'+esc(cityName(c))+'</h1><p>'+total.toLocaleString()+' '+tr('places')+'</p></div></div></section><section class="section"><div class="shell">'+(places.places.length?'<div class="grid">'+places.places.map(placeCard).join('')+'</div>'+pages:'<div class="empty">'+tr('notFound')+'</div>')+'</div></section></main>'+footer()
}

async function restaurantPage(){
 const id=new URLSearchParams(location.search).get('id'),r=await api('place',{id});
 const lat=Number(r.latitude),lon=Number(r.longitude),hasCoords=Number.isFinite(lat)&&Number.isFinite(lon)&&r.latitude!=null&&r.longitude!=null;
 const seen=new Set(),photos=(r.photos||[]).filter(x=>x?.image_url&&!seen.has(x.image_url)&&seen.add(x.image_url)).slice(0,10); const address=(r.sources||[]).map(x=>x.address_text).find(Boolean)||'';
 const destination=hasCoords?(lat+','+lon):([address,cityName(r)].filter(Boolean).join(', '));
 const gmaps='https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(destination);
 const waze=hasCoords?('https://www.waze.com/ul?ll='+encodeURIComponent(lat+','+lon)+'&navigate=yes'):('https://www.waze.com/ul?q='+encodeURIComponent(destination)+'&navigate=yes');
 const gallery=photos.length>1?'<h2 class="galleryTitle">'+tr('gallery')+'</h2><div class="photoGallery">'+photos.map((p,i)=>'<a href="'+esc(p.image_url)+'" target="_blank" rel="noopener" class="galleryItem"><img src="'+esc(p.image_url)+'" alt="'+esc(placeName(r))+' '+(i+1)+'" loading="lazy" referrerpolicy="no-referrer"></a>').join('')+'</div>':'';
 const hero=r.photo_url?'<div class="detailPhoto"><img src="'+esc(r.photo_url)+'" alt="'+esc(placeName(r))+'" referrerpolicy="no-referrer"></div>':'<div class="detailPhoto noPhoto detailNoPhoto"><span>'+icon(r.category)+'</span><small>'+tr('noPhoto')+'</small></div>';
 return nav()+'<main><section class="detailHero"><div class="shell"><a class="link" href="javascript:history.back()">'+tr('back')+'</a><div class="detailWrap"><div class="detailMain">'+hero+'<div class="restaurantTitle"><div><span class="goldKicker">'+esc(categoryName(r.category))+'</span><h1>'+esc(placeName(r))+'</h1><div class="detailMeta">'+esc(cityName(r))+'</div></div></div>'+gallery+'<h2 class="subTitle">'+tr('source')+'</h2><div class="sourceGrid">'+(r.sources||[]).map(s=>'<div class="sourceBox"><strong>'+esc(String(s.source_code).toUpperCase())+'</strong><span>'+esc(s.source_entity_id)+'</span></div>').join('')+'</div></div><aside class="sideCard"><h3>'+tr('info')+'</h3>'+(r.phone?'<div class="infoLine"><b>☎</b><span><strong>'+tr('phone')+'</strong><br><a href="tel:'+esc(r.phone)+'">'+esc(r.phone)+'</a></span></div>':'')+(r.website?'<div class="infoLine"><b>↗</b><span><strong>'+tr('website')+'</strong><br><a class="link" href="'+esc(r.website)+'" target="_blank" rel="noopener">'+esc(r.website)+'</a></span></div>':'')+(address?'<div class="infoLine"><b>⌂</b><span><strong>'+tr('address')+'</strong><br>'+esc(address)+'</span></div>':'')+(hasCoords?'<div class="infoLine"><b>⌖</b><span><strong>'+tr('coordinates')+'</strong><br>'+lat.toFixed(6)+', '+lon.toFixed(6)+'</span></div>':'')+'<h3 class="navTitle">'+tr('navigate')+'</h3><div class="navButtons"><a class="navBtn google" href="'+gmaps+'" target="_blank" rel="noopener"><span>G</span>'+tr('googleMaps')+'</a><a class="navBtn waze" href="'+waze+'" target="_blank" rel="noopener"><span>W</span>'+tr('waze')+'</a></div></aside></div></div></section></main>'+footer()
}

function goSearch(e){e.preventDefault();location.href='search.html?q='+encodeURIComponent(document.getElementById('q').value)+'&city='+encodeURIComponent(document.getElementById('city').value);return false}
function filterSearch(e){e.preventDefault();location.href='search.html?q='+encodeURIComponent(document.getElementById('fq').value)+'&city='+encodeURIComponent(document.getElementById('fcity').value)+'&category='+encodeURIComponent(document.getElementById('fcategory').value);return false}
async function renderPage(){const root=document.getElementById('app');document.documentElement.lang=lang;document.documentElement.dir=lang==='he'?'rtl':'ltr';root.innerHTML=loading();try{const p=document.body.dataset.page;root.innerHTML=await(p==='search'?searchPage():p==='restaurant'?restaurantPage():p==='city'?cityPage():home())}catch(e){console.error(e);root.innerHTML=nav()+'<main class="section"><div class="shell"><div class="empty">'+tr('notFound')+'</div></div></main>'+footer()}document.querySelectorAll('.lang').forEach(b=>{b.classList.toggle('active',b.dataset.lang===lang);b.onclick=()=>setLang(b.dataset.lang)})}
document.addEventListener('DOMContentLoaded',renderPage);