const API_BASE='https://br-autumn-rice-b5twaf7e-catalogapi.compute.c-7.us-east-2.aws.neon.tech';

const UI={
ru:{navExplore:'Все точки',navCities:'Города',heroBadge:'LIVE · КАТАЛОГ ИЗРАИЛЯ',heroTitle:'Весь Израиль. Все места. Один каталог.',heroSub:'Рестораны, фастфуд, кафе, супермаркеты, минимаркеты, магазины и другие реальные точки — с фото, координатами и навигацией.',searchPh:'Название места или бизнеса…',cityAll:'Весь Израиль',search:'Найти',stat1:'официальных населённых пунктов',stat2:'точек в живом каталоге',stat3:'населённых пунктов с точками',stat4:'языка интерфейса',livePlaces:'Реальные места',liveSub:'Живые данные из базы FoodRate Israel',cities:'Города и населённые пункты',citiesSub:'Каталог по всей стране',view:'Открыть',places:'точек',results:'Результаты поиска',all:'Все категории',details:'Открыть карточку',info:'Информация',phone:'Телефон',website:'Сайт',coordinates:'Координаты',address:'Адрес',source:'Источники данных',back:'← Назад',loading:'Загружаю каталог…',notFound:'Ничего не найдено. Измените запрос или фильтр.',live:'LIVE',dataNote:'FoodRate Israel — живой каталог мест Израиля. Данные объединяются из открытых и разрешённых источников и постоянно уточняются.',gallery:'Фотографии места',googleMaps:'Google Maps',waze:'Waze',navigate:'Навигация',noPhoto:'Фото пока не найдено',categories:'Категории',categoriesSub:'Быстрый переход к нужному типу места'},
he:{navExplore:'כל המקומות',navCities:'יישובים',heroBadge:'LIVE · מדריך ישראל',heroTitle:'כל ישראל. כל המקומות. מדריך אחד.',heroSub:'מסעדות, מזון מהיר, בתי קפה, סופרמרקטים, מכולות, חנויות ועוד — עם תמונות, מיקום וניווט.',searchPh:'שם מקום או עסק…',cityAll:'כל ישראל',search:'חיפוש',stat1:'יישובים רשמיים',stat2:'נקודות במאגר החי',stat3:'יישובים עם נקודות',stat4:'שפות בממשק',livePlaces:'מקומות אמיתיים',liveSub:'נתונים חיים ממאגר FoodRate Israel',cities:'ערים ויישובים',citiesSub:'מדריך לכל הארץ',view:'פתיחה',places:'מקומות',results:'תוצאות חיפוש',all:'כל הקטגוריות',details:'פתיחת כרטיס',info:'מידע',phone:'טלפון',website:'אתר',coordinates:'קואורדינטות',address:'כתובת',source:'מקורות מידע',back:'→ חזרה',loading:'טוען את המאגר…',notFound:'לא נמצאו תוצאות. נסו חיפוש או סינון אחר.',live:'LIVE',dataNote:'FoodRate Israel — מדריך חי למקומות בישראל. הנתונים נאספים ממקורות פתוחים ומורשים ומתעדכנים באופן שוטף.',gallery:'תמונות המקום',googleMaps:'Google Maps',waze:'Waze',navigate:'ניווט',noPhoto:'עדיין אין תמונה',categories:'קטגוריות',categoriesSub:'גישה מהירה לסוג המקום שאתם מחפשים'},
en:{navExplore:'All places',navCities:'Localities',heroBadge:'LIVE · ISRAEL DIRECTORY',heroTitle:'All of Israel. Every place. One directory.',heroSub:'Restaurants, fast food, cafés, supermarkets, convenience stores, shops and more — with photos, coordinates and navigation.',searchPh:'Place or business name…',cityAll:'All Israel',search:'Search',stat1:'official localities',stat2:'places in the live catalog',stat3:'localities with places',stat4:'interface languages',livePlaces:'Real places',liveSub:'Live data from FoodRate Israel',cities:'Cities and localities',citiesSub:'Nationwide discovery',view:'Open',places:'places',results:'Search results',all:'All categories',details:'Open listing',info:'Information',phone:'Phone',website:'Website',coordinates:'Coordinates',address:'Address',source:'Data sources',back:'← Back',loading:'Loading catalog…',notFound:'Nothing found. Change the query or filter.',live:'LIVE',dataNote:'FoodRate Israel is a live directory of places in Israel. Data is merged from open and permitted sources and continuously refined.',gallery:'Place photos',googleMaps:'Google Maps',waze:'Waze',navigate:'Navigation',noPhoto:'Photo not found yet',categories:'Categories',categoriesSub:'Jump straight to the kind of place you need'}
};

const CAT={
'amenity:restaurant':['Ресторан','מסעדה','Restaurant'],'amenity:cafe':['Кафе','בית קפה','Cafe'],'amenity:fast_food':['Фастфуд','מזון מהיר','Fast food'],'amenity:bar':['Бар','בר','Bar'],'amenity:pub':['Паб','פאב','Pub'],'amenity:food_court':['Фуд-корт','מתחם אוכל','Food court'],'amenity:ice_cream':['Мороженое','גלידה','Ice cream'],
'shop:bakery':['Пекарня','מאפייה','Bakery'],'shop:confectionery':['Кондитерская','קונדיטוריה','Confectionery'],'shop:supermarket':['Супермаркет','סופרמרקט','Supermarket'],'shop:convenience':['Минимаркет','מכולת','Convenience store'],'shop:kiosk':['Киоск','קיוסק','Kiosk'],'shop:butcher':['Мясной магазин','אטליז','Butcher'],'shop:greengrocer':['Овощи и фрукты','ירקן','Greengrocer'],
'amenity:pharmacy':['Аптека','בית מרקחת','Pharmacy'],'amenity:fuel':['АЗС','תחנת דלק','Fuel station'],'amenity:bank':['Банк','בנק','Bank'],'amenity:clinic':['Клиника','מרפאה','Clinic'],'tourism:hotel':['Отель','מלון','Hotel']
};

const GROUPS=[
['🍽️','amenity:restaurant','Рестораны','מסעדות','Restaurants'],
['🥙','amenity:fast_food','Фастфуд','מזון מהיר','Fast food'],
['☕','amenity:cafe','Кафе','בתי קפה','Cafés'],
['🛒','shop:supermarket','Супермаркеты','סופרמרקטים','Supermarkets'],
['🏪','shop:convenience','Минимаркеты','מכולות','Convenience'],
['🥐','shop:bakery','Пекарни','מאפיות','Bakeries'],
['💊','amenity:pharmacy','Аптеки','בתי מרקחת','Pharmacies'],
['🛍️','shop:','Все магазины','כל החנויות','All shops']
];

let lang=localStorage.getItem('foodrate-lang')||'ru';
const tr=k=>UI[lang][k]||k;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const qs=o=>new URLSearchParams(Object.entries(o).filter(([,v])=>v!==''&&v!=null)).toString();
async function api(route,params={}){const r=await fetch(API_BASE+'/'+route+(Object.keys(params).length?'?'+qs(params):''));if(!r.ok)throw new Error('API '+r.status);return r.json()}
function setLang(l){lang=l;localStorage.setItem('foodrate-lang',l);document.documentElement.lang=l;document.documentElement.dir=l==='he'?'rtl':'ltr';renderPage()}
function cityName(c){const fallback=lang==='he'?'ישראל':lang==='ru'?'Израиль':'Israel';return lang==='he'?(c.name_he||c.city_he||c.name_en||c.city_en||fallback):lang==='ru'?(c.name_ru||c.city_ru||c.name_en||c.city_en||c.name_he||c.city_he||fallback):(c.name_en||c.city_en||c.name_he||c.city_he||fallback)}
function placeName(p){return lang==='he'?(p.name_he||p.primary_name):lang==='ru'?(p.name_ru||p.name_he||p.name_en||p.primary_name):(p.name_en||p.primary_name||p.name_he)}
function categoryName(v){const a=CAT[v];return a?(lang==='ru'?a[0]:lang==='he'?a[1]:a[2]):String(v||'').replace(/^.*:/,'').replaceAll('_',' ')}
function icon(v){if(v==='amenity:restaurant')return'🍽️';if(v==='amenity:cafe')return'☕';if(v==='amenity:fast_food')return'🥙';if(v==='shop:bakery')return'🥐';if(v?.startsWith('shop:'))return'🛍️';if(v==='amenity:pharmacy')return'💊';if(v==='amenity:fuel')return'⛽';if(v==='amenity:bar'||v==='amenity:pub')return'🍸';if(v?.startsWith('tourism:'))return'🏨';return'📍'}
function groupLabel(g){return lang==='ru'?g[2]:lang==='he'?g[3]:g[4]}
function nav(){return '<header class="topbar"><div class="shell nav"><a class="brand" href="index.html"><img class="brandLogo" src="logo.svg" alt="FoodRate Israel"></a><nav class="navlinks"><a href="search.html">'+tr('navExplore')+'</a><a href="index.html#cities">'+tr('navCities')+'</a></nav><div class="navtools"><button class="lang" data-lang="he">עברית</button><button class="lang" data-lang="ru">RU</button><button class="lang" data-lang="en">EN</button></div></div></header>'}
function footer(){return '<footer class="footer"><div class="shell footerIn"><img src="logo.svg" class="footerLogo" alt="FoodRate Israel"><div class="legal">'+tr('dataNote')+'<br>© OpenStreetMap contributors</div></div></footer>'}
function loading(){return nav()+'<main class="section"><div class="shell"><div class="empty">'+tr('loading')+'</div></div></main>'+footer()}
function photo(p){return p.photo_url?'<img src="'+esc(p.photo_url)+'" alt="'+esc(placeName(p))+'" loading="lazy" referrerpolicy="no-referrer">':'<div class="noPhoto"><span>'+icon(p.category)+'</span><small>'+tr('noPhoto')+'</small></div>'}
function placeCard(p){return '<a class="card" href="restaurant.html?id='+encodeURIComponent(p.id)+'"><div class="cover">'+photo(p)+'<span class="badge">'+esc(categoryName(p.category))+'</span></div><div class="cardbody"><div class="cardtop"><div><h3>'+esc(placeName(p))+'</h3><div class="meta">'+esc(cityName(p))+'</div></div><span class="liveDot">LIVE</span></div><div class="tags">'+esc(categoryName(p.category))+(p.phone?' · '+esc(p.phone):'')+'</div><div class="dishrow"><span>'+tr('details')+'</span><strong>↗</strong></div></div></a>'}
function cityCard(c){return '<a class="city" href="city.html?id='+encodeURIComponent(c.official_code)+'"><span class="cityPin">◆</span><strong>'+esc(cityName(c))+'</strong><span>'+Number(c.places||0).toLocaleString()+' '+tr('places')+'</span><b>'+tr('view')+' →</b></a>'}
function categoryStrip(){return '<section class="section"><div class="shell"><div class="sectionHead"><div><span class="goldKicker">'+tr('categories')+'</span><h2>'+tr('categories')+'</h2><p>'+tr('categoriesSub')+'</p></div></div><div class="categoryGrid">'+GROUPS.map(g=>'<a class="categoryTile" href="search.html?category='+encodeURIComponent(g[1])+'"><span>'+g[0]+'</span><strong>'+esc(groupLabel(g))+'</strong></a>').join('')+'</div></div></section>'}
function pager(total,page,size,params,base){const pages=Math.max(1,Math.ceil(Number(total||0)/size));if(pages<=1)return'';const label=lang==='he'?'עמוד':lang==='ru'?'Страница':'Page';const prev=lang==='he'?'הקודם':lang==='ru'?'Назад':'Previous';const next=lang==='he'?'הבא':lang==='ru'?'Вперёд':'Next';const href=n=>base+'?'+qs({...params,page:n});return '<nav class="pager">'+(page>1?'<a class="pageBtn" href="'+href(page-1)+'">← '+prev+'</a>':'<span></span>')+'<strong>'+label+' '+page+' / '+pages+'</strong>'+(page<pages?'<a class="pageBtn" href="'+href(page+1)+'">'+next+' →</a>':'<span></span>')+'</nav>'}

async function home(){
 const [stats,cities,places]=await Promise.all([api('stats'),api('cities',{limit:8}),api('places',{limit:9})]);
 return nav()+'<main><section class="hero"><div class="shell"><div class="heroPanel"><div class="heroGlow red"></div><div class="heroGlow blue"></div><span class="eyebrow"><i></i>'+tr('heroBadge')+'</span><img src="logo.svg" class="heroLogo" alt="FoodRate Israel"><h1>'+tr('heroTitle')+'</h1><p>'+tr('heroSub')+'</p><form class="searchbar" onsubmit="return goSearch(event)"><div class="field">⌕<input id="q" placeholder="'+tr('searchPh')+'"></div><div class="field">⌖<select id="city"><option value="">'+tr('cityAll')+'</option>'+cities.cities.map(c=>'<option value="'+esc(c.official_code)+'">'+esc(cityName(c))+'</option>').join('')+'</select></div><button class="primary">'+tr('search')+'</button></form></div><div class="stats"><div class="stat"><strong>'+Number(stats.localities).toLocaleString()+'</strong><span>'+tr('stat1')+'</span></div><div class="stat"><strong>'+Number(stats.places).toLocaleString()+'</strong><span>'+tr('stat2')+'</span></div><div class="stat"><strong>'+Number(stats.localities_with_places).toLocaleString()+'</strong><span>'+tr('stat3')+'</span></div><div class="stat"><strong>3</strong><span>'+tr('stat4')+'</span></div></div></div></section>'+categoryStrip()+'<section class="section"><div class="shell"><div class="sectionHead"><div><span class="goldKicker">DISCOVER</span><h2>'+tr('livePlaces')+'</h2><p>'+tr('liveSub')+'</p></div><a class="link" href="search.html">'+tr('view')+'</a></div><div class="grid">'+places.places.map(placeCard).join('')+'</div></div></section><section class="section" id="cities"><div class="shell"><div class="sectionHead"><div><span class="goldKicker">ISRAEL</span><h2>'+tr('cities')+'</h2><p>'+tr('citiesSub')+'</p></div></div><div class="cityGrid">'+cities.cities.map(cityCard).join('')+'</div></div></section></main>'+footer()
}

async function searchPage(){
 const p=new URLSearchParams(location.search),q=p.get('q')||'',city=p.get('city')||'',category=p.get('category')||'',page=Math.max(1,Number(p.get('page')||1)),size=60,offset=(page-1)*size;
 const [cities,places]=await Promise.all([api('cities',{limit:1400}),api('places',{q,city,category,limit:size,offset})]);
 const total=Number(places.total??places.count??0),pages=pager(total,page,size,{q,city,category},'search.html');
 return nav()+'<main class="section"><div class="shell"><div class="sectionHead"><div><span class="goldKicker">SEARCH</span><h2>'+tr('results')+'</h2><p>'+total.toLocaleString()+' '+tr('places')+'</p></div></div><form class="filterPanel" onsubmit="return filterSearch(event)"><input id="fq" value="'+esc(q)+'" placeholder="'+tr('searchPh')+'"><select id="fcity"><option value="">'+tr('cityAll')+'</option>'+cities.cities.map(c=>'<option value="'+esc(c.official_code)+'" '+(city===String(c.official_code)?'selected':'')+'>'+esc(cityName(c))+' ('+Number(c.places||0)+')</option>').join('')+'</select><select id="fcategory"><option value="">'+tr('all')+'</option>'+GROUPS.map(g=>'<option value="'+esc(g[1])+'" '+(category===g[1]?'selected':'')+'>'+g[0]+' '+esc(groupLabel(g))+'</option>').join('')+'</select><button class="primary">'+tr('search')+'</button></form>'+(places.places.length?'<div class="grid">'+places.places.map(placeCard).join('')+'</div>'+pages:'<div class="empty">'+tr('notFound')+'</div>')+'</div></main>'+footer()
}

async function cityPage(){
 const p=new URLSearchParams(location.search),id=p.get('id')||'',page=Math.max(1,Number(p.get('page')||1)),size=60,offset=(page-1)*size;
 const [cities,places]=await Promise.all([api('cities',{limit:1400}),api('places',{city:id,limit:size,offset})]);
 const c=cities.cities.find(x=>String(x.official_code)===String(id));
 if(!c)return nav()+'<main class="section"><div class="shell"><div class="empty">'+tr('notFound')+'</div></div></main>'+footer();
 const total=Number(places.total??c.places??0),pages=pager(total,page,size,{id},'city.html');
 return nav()+'<main><section class="detailHero"><div class="shell"><div class="cityHero"><span class="goldKicker">LOCAL DIRECTORY</span><h1>'+esc(cityName(c))+'</h1><p>'+total.toLocaleString()+' '+tr('places')+'</p></div></div></section><section class="section"><div class="shell">'+(places.places.length?'<div class="grid">'+places.places.map(placeCard).join('')+'</div>'+pages:'<div class="empty">'+tr('notFound')+'</div>')+'</div></section></main>'+footer()
}

async function restaurantPage(){
 const id=new URLSearchParams(location.search).get('id'),r=await api('place',{id});
 const lat=Number(r.latitude),lon=Number(r.longitude),hasCoords=Number.isFinite(lat)&&Number.isFinite(lon)&&r.latitude!=null&&r.longitude!=null;
 const seen=new Set(),photos=(r.photos||[]).filter(x=>x?.image_url&&!seen.has(x.image_url)&&seen.add(x.image_url)).slice(0,10); const address=(r.sources||[]).map(x=>x.address_text).find(Boolean)||'';
 const destination=hasCoords?(lat+','+lon):([address,cityName(r)].filter(Boolean).join(', '));
 const gmaps='https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(destination);
 const waze=hasCoords?('https://www.waze.com/ul?ll='+encodeURIComponent(lat+','+lon)+'&navigate=yes'):('https://www.waze.com/ul?q='+encodeURIComponent(destination)+'&navigate=yes');
 const gallery=photos.length>1?'<h2 class="galleryTitle">'+tr('gallery')+'</h2><div class="photoGallery">'+photos.map((p,i)=>'<a href="'+esc(p.image_url)+'" target="_blank" rel="noopener" class="galleryItem"><img src="'+esc(p.image_url)+'" alt="'+esc(placeName(r))+' '+(i+1)+'" loading="lazy" referrerpolicy="no-referrer"></a>').join('')+'</div>':'';
 const hero=r.photo_url?'<div class="detailPhoto"><img src="'+esc(r.photo_url)+'" alt="'+esc(placeName(r))+'" referrerpolicy="no-referrer"></div>':'<div class="detailPhoto noPhoto detailNoPhoto"><span>'+icon(r.category)+'</span><small>'+tr('noPhoto')+'</small></div>';
 return nav()+'<main><section class="detailHero"><div class="shell"><a class="link" href="javascript:history.back()">'+tr('back')+'</a><div class="detailWrap"><div class="detailMain">'+hero+'<div class="restaurantTitle"><div><span class="goldKicker">'+esc(categoryName(r.category))+'</span><h1>'+esc(placeName(r))+'</h1><div class="detailMeta">'+esc(cityName(r))+'</div></div><span class="livePill">'+tr('live')+'</span></div>'+gallery+'<h2 class="subTitle">'+tr('source')+'</h2><div class="sourceGrid">'+(r.sources||[]).map(s=>'<div class="sourceBox"><strong>'+esc(String(s.source_code).toUpperCase())+'</strong><span>'+esc(s.source_entity_id)+'</span></div>').join('')+'</div></div><aside class="sideCard"><h3>'+tr('info')+'</h3>'+(r.phone?'<div class="infoLine"><b>☎</b><span><strong>'+tr('phone')+'</strong><br><a href="tel:'+esc(r.phone)+'">'+esc(r.phone)+'</a></span></div>':'')+(r.website?'<div class="infoLine"><b>↗</b><span><strong>'+tr('website')+'</strong><br><a class="link" href="'+esc(r.website)+'" target="_blank" rel="noopener">'+esc(r.website)+'</a></span></div>':'')+(address?'<div class="infoLine"><b>⌂</b><span><strong>'+tr('address')+'</strong><br>'+esc(address)+'</span></div>':'')+(hasCoords?'<div class="infoLine"><b>⌖</b><span><strong>'+tr('coordinates')+'</strong><br>'+lat.toFixed(6)+', '+lon.toFixed(6)+'</span></div>':'')+'<h3 class="navTitle">'+tr('navigate')+'</h3><div class="navButtons"><a class="navBtn google" href="'+gmaps+'" target="_blank" rel="noopener"><span>G</span>'+tr('googleMaps')+'</a><a class="navBtn waze" href="'+waze+'" target="_blank" rel="noopener"><span>W</span>'+tr('waze')+'</a></div></aside></div></div></section></main>'+footer()
}

function goSearch(e){e.preventDefault();location.href='search.html?q='+encodeURIComponent(document.getElementById('q').value)+'&city='+encodeURIComponent(document.getElementById('city').value);return false}
function filterSearch(e){e.preventDefault();location.href='search.html?q='+encodeURIComponent(document.getElementById('fq').value)+'&city='+encodeURIComponent(document.getElementById('fcity').value)+'&category='+encodeURIComponent(document.getElementById('fcategory').value);return false}
async function renderPage(){const root=document.getElementById('app');document.documentElement.lang=lang;document.documentElement.dir=lang==='he'?'rtl':'ltr';root.innerHTML=loading();try{const p=document.body.dataset.page;root.innerHTML=await(p==='search'?searchPage():p==='restaurant'?restaurantPage():p==='city'?cityPage():home())}catch(e){console.error(e);root.innerHTML=nav()+'<main class="section"><div class="shell"><div class="empty">'+tr('notFound')+'</div></div></main>'+footer()}document.querySelectorAll('.lang').forEach(b=>{b.classList.toggle('active',b.dataset.lang===lang);b.onclick=()=>setLang(b.dataset.lang)})}
document.addEventListener('DOMContentLoaded',renderPage);