window.FOOD_DATA = {
  cities:[
    {id:'tel-aviv',ru:'Тель-Авив',he:'תל אביב',en:'Tel Aviv',count:1248,icon:'🌆'},
    {id:'jerusalem',ru:'Иерусалим',he:'ירושלים',en:'Jerusalem',count:1016,icon:'🕌'},
    {id:'haifa',ru:'Хайфа',he:'חיפה',en:'Haifa',count:684,icon:'🌊'},
    {id:'beer-sheva',ru:'Беэр-Шева',he:'באר שבע',en:'Beer Sheva',count:391,icon:'🌵'}
  ],
  restaurants:[
    {id:'shuk-grill',emoji:'🥙',ru:'Shuk Grill',he:'שוק גריל',en:'Shuk Grill',city:'tel-aviv',type:{ru:'Шаурма · Ближневосточная',he:'שווארמה · מזרח תיכוני',en:'Shawarma · Middle Eastern'},score:9.2,price:'₪₪',kosher:true,open:true,delivery:true,sources:[['Google','4.7','2.8K'],['Wolt','9.4','1.4K'],['FoodRate','9.1','386']],bestDish:{ru:'Шаурма из индейки',he:'שווארמה הודו',en:'Turkey shawarma',score:9.5},tags:{ru:['Кошерное','Доставка','До позднего'],he:['כשר','משלוחים','פתוח מאוחר'],en:['Kosher','Delivery','Open late']},address:{ru:'ул. Алленби 74, Тель-Авив',he:'אלנבי 74, תל אביב',en:'74 Allenby St, Tel Aviv'},hours:'11:00–01:00',phone:'03-555-0124',dishes:[['🥙','Шаурма / שווארמה / Shawarma',9.5],['🧆','Фалафель / פלאפל / Falafel',9.1],['🥗','Салаты / סלטים / Salads',8.8],['🍟','Картофель / צ׳יפס / Fries',8.6]],reviews:[['Maya',9.6,'Очень сочное мясо, большая порция и быстрая подача.'],['Daniel',9.1,'Strong shawarma, clean place and fair price.'],['נועם',9.4,'טעים מאוד, שירות מהיר והמנה גדולה.']]},
    {id:'nori-house',emoji:'🍣',ru:'Nori House',he:'נורי האוס',en:'Nori House',city:'haifa',type:{ru:'Суши · Японская',he:'סושי · יפני',en:'Sushi · Japanese'},score:8.9,price:'₪₪₪',kosher:false,open:true,delivery:true,sources:[['Google','4.6','1.1K'],['Tripadvisor','4.5','430'],['FoodRate','8.8','204']],bestDish:{ru:'Salmon Crunch Roll',he:'סלמון קראנץ׳ רול',en:'Salmon Crunch Roll',score:9.3},tags:{ru:['Доставка','Vegan options','Море рядом'],he:['משלוחים','אפשרויות טבעוניות','ליד הים'],en:['Delivery','Vegan options','Near the sea']},address:{ru:'пр. Ха-Наси 112, Хайфа',he:'הנשיא 112, חיפה',en:'112 HaNassi Blvd, Haifa'},hours:'12:00–23:30',phone:'04-555-0138',dishes:[['🍣','Salmon Crunch Roll',9.3],['🍱','Sushi Set',8.9],['🥢','Gyoza',8.5],['🌱','Vegan Roll',8.8]],reviews:[['Alex',9.2,'Свежая рыба и очень аккуратная подача.'],['Shira',8.8,'טעים, טרי ושירות נעים.'],['James',8.7,'Good sushi and a calm atmosphere.']]},
    {id:'urban-bun',emoji:'🍔',ru:'Urban Bun',he:'אורבן באן',en:'Urban Bun',city:'jerusalem',type:{ru:'Бургеры · Street food',he:'המבורגרים · אוכל רחוב',en:'Burgers · Street food'},score:8.7,price:'₪₪',kosher:true,open:true,delivery:true,sources:[['Google','4.5','1.9K'],['Wolt','9.0','980'],['FoodRate','8.6','311']],bestDish:{ru:'Smash Burger',he:'סמאש בורגר',en:'Smash Burger',score:9.1},tags:{ru:['Кошерное','Доставка','Открыто допоздна'],he:['כשר','משלוחים','פתוח מאוחר'],en:['Kosher','Delivery','Open late']},address:{ru:'ул. Яффо 38, Иерусалим',he:'יפו 38, ירושלים',en:'38 Jaffa St, Jerusalem'},hours:'11:30–00:30',phone:'02-555-0177',dishes:[['🍔','Smash Burger',9.1],['🧀','Cheese Burger',8.7],['🍟','Loaded Fries',8.8],['🥤','Milkshake',8.3]],reviews:[['Oleg',8.9,'Бургер отличный, картошка тоже сильная.'],['Yael',8.6,'שירות מהיר והמבורגר עסיסי.'],['Chris',8.5,'Very solid late-night burger.']]},
    {id:'pasta-lab',emoji:'🍝',ru:'Pasta Lab',he:'פסטה לאב',en:'Pasta Lab',city:'tel-aviv',type:{ru:'Итальянская · Паста',he:'איטלקי · פסטה',en:'Italian · Pasta'},score:8.8,price:'₪₪₪',kosher:false,open:true,delivery:false,sources:[['Google','4.6','740'],['Tripadvisor','4.4','215'],['FoodRate','8.9','164']],bestDish:{ru:'Truffle Tagliatelle',he:'טליאטלה כמהין',en:'Truffle Tagliatelle',score:9.4},tags:{ru:['Паста ручной работы','Бронирование','Вино'],he:['פסטה עבודת יד','הזמנות','יין'],en:['Handmade pasta','Reservations','Wine']},address:{ru:'ул. Дизенгоф 155, Тель-Авив',he:'דיזנגוף 155, תל אביב',en:'155 Dizengoff St, Tel Aviv'},hours:'12:00–23:30',phone:'03-555-0199',dishes:[['🍝','Truffle Tagliatelle',9.4],['🍅','Pomodoro',8.9],['🧀','Ravioli',9.0],['🍰','Tiramisu',8.7]],reviews:[['Irina',9.1,'Очень приятная паста и хорошая атмосфера.'],['Ron',8.9,'פסטה מצוינת ואווירה טובה.'],['Sophie',8.8,'Lovely handmade pasta and attentive service.']]},
    {id:'green-table',emoji:'🌱',ru:'Green Table',he:'גרין טייבל',en:'Green Table',city:'beer-sheva',type:{ru:'Vegan · Healthy',he:'טבעוני · בריא',en:'Vegan · Healthy'},score:8.6,price:'₪₪',kosher:true,open:false,delivery:true,sources:[['Google','4.5','512'],['HappyCow','4.7','182'],['FoodRate','8.5','99']],bestDish:{ru:'Vegan Bowl',he:'קערה טבעונית',en:'Vegan Bowl',score:9.0},tags:{ru:['Веганское','Кошерное','Gluten-free options'],he:['טבעוני','כשר','אפשרויות ללא גלוטן'],en:['Vegan','Kosher','Gluten-free options']},address:{ru:'ул. Рагер 28, Беэр-Шева',he:'רגר 28, באר שבע',en:'28 Rager Blvd, Beer Sheva'},hours:'09:00–21:00',phone:'08-555-0114',dishes:[['🥗','Vegan Bowl',9.0],['🥑','Avocado Toast',8.7],['🍲','Lentil Soup',8.5],['🍪','Tahini Cookie',8.4]],reviews:[['Anna',8.8,'Хороший выбор веганских блюд.'],['עדי',8.7,'טרי, טעים ויש הרבה אופציות.'],['Ben',8.3,'Fresh and easy healthy lunch.']]},
    {id:'jerusalem-coffee',emoji:'☕',ru:'Jerusalem Coffee',he:'קפה ירושלים',en:'Jerusalem Coffee',city:'jerusalem',type:{ru:'Кофейня · Выпечка',he:'בית קפה · מאפים',en:'Coffee · Bakery'},score:9.0,price:'₪₪',kosher:true,open:true,delivery:false,sources:[['Google','4.8','1.6K'],['Tripadvisor','4.6','301'],['FoodRate','8.9','228']],bestDish:{ru:'Круассан с миндалём',he:'קרואסון שקדים',en:'Almond croissant',score:9.4},tags:{ru:['Кошерное','Завтраки','Wi-Fi'],he:['כשר','ארוחות בוקר','Wi‑Fi'],en:['Kosher','Breakfast','Wi‑Fi']},address:{ru:'ул. Кинг Джордж 18, Иерусалим',he:'קינג ג׳ורג׳ 18, ירושלים',en:'18 King George St, Jerusalem'},hours:'07:30–20:30',phone:'02-555-0128',dishes:[['☕','Flat White',9.2],['🥐','Almond Croissant',9.4],['🥪','Breakfast Sandwich',8.8],['🍰','Cheesecake',8.9]],reviews:[['Nina',9.2,'Отличный кофе и свежая выпечка.'],['דני',9.0,'קפה מעולה ואווירה נעימה.'],['Mark',9.1,'Excellent coffee and pastries.']]}
  ]
};